# Generated by Django 3.2 on 2021-05-24 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Technique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technique_type', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=5000)),
                ('accuracy', models.IntegerField(default=0)),
                ('precision', models.IntegerField(default=0)),
                ('recall', models.IntegerField(default=0)),
                ('url', models.CharField(max_length=500)),
                ('confusionMatrix', models.ImageField(upload_to='')),
                ('descImage', models.ImageField(upload_to='')),
            ],
        ),
    ]
